### ISSUE TITLE
pkg install throws "not available (for..." 

### ISSUE THREAD

**Issue by ds4ci** [ehrlinger/ggRandomForests#24]
On Win8 64 bit RStudio, throws for R 3.2.0, R 3.1.3, & below:
> install.packages("ggRandomForest")
Installing package into ‘C:/Users/Jim/Documents/R/win-library/3.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘ggRandomForest’ is not available (for R version 3.1.2)
> 
using both RStudio global CRAN and IA CRAN
Tnx, Jim

**Comment by ehrlinger** [comment]
For some silly reason, I named the package with a trailing ’s’ character. Try:

> install.packages("ggRandomForests")
> 
Which should work on any platform as there is no compiled code. (yet)

Thanks
John

**Comment by ds4ci** [comment]
John,

Which I should have caught, since I was looking at the CRAN page!
( guess I'll beat up on R/RStudio for throwing misleading message)

Sorry to disturb.

-Jim

**Comment by ehrlinger** [comment]
No trouble. That would be hard for R/Rstudio to catch. Though I have seen it catch incorrect case (like ggrandomforests), misspelling would be much more difficult.

I’ll close this.
John
