### ISSUE TITLE
conditioning a coplot on a factor 

### ISSUE THREAD

**Issue by rshouv** [ehrlinger/ggRandomForests#27]
Hello.
In the ggRandomForests: Exploring Random Forest Survival paper, there is a partial dependence coplot of 1 year survival against bilirubin,conditional on albumin interval group membership (figure 24)
I am trying to create a similar cotplot, but instead of conditioning on albumin intervals, I would like to condition on a variable that was originally categorized (for instance edema or ascites). I tried doing so to but could not get the script right. 
Would deeply appreciate your help in this matter.
Thanks
Roni

**Comment by ehrlinger** [comment]
Can I see your script? I might also need to see a summary of your training data set so I can figure out what is going on.

**Comment by rshouv** [comment]
Hey,
For the example Ive chosen the pbc data set. I Would like create a partial plot for 1 year survival, plotted against bilirubin and conditional on edema. I've tried the following script, and it doesn't work. 


# Load the forest
data(rfsrc_pbc, package="ggRandomForests")
# Create the variable plot.
ggvar <- gg_variable(rfsrc_pbc, time = 1)

partial_coplot_pbc <- gg_partial_coplot(rfsrc_pbc, xvar = "bili",groups =edema,
surv_type = "surv",
time = 1,
show.plots = FALSE)

plot(partial_coplot_pbc, se = FALSE)

# thanks!

**Comment by ehrlinger** [comment]
Alright. What you need is:

``` 
data(rfsrc_pbc, package="ggRandomForests")

# This is a bit of a hack, but you need a factor vector of the same length as the training data
edema <- factor(rfsrc_pbc$xvar$edema)

# Then the plot will recalculate the predicted values.
partial_coplot_pbc <- gg_partial_coplot(rfsrc_pbc, xvar = "bili",groups =edema,
                                                               surv_type = "surv",
                                                               time = 1,
                                                               show.plots = FALSE)

# And the plot
plot(partial_coplot_pbc, se = FALSE)
```

**Comment by ehrlinger** [comment]
Also, the demo files are extremely fragile. If you get an error that looks something like this:
```
Error in generic.predict.rfsrc(object, newdata, importance = importance,  : 
  An error has occurred in prediction.  Please turn trace on for further analysis. 
```

It means there is an randomForestSRC version incompatibility between the provided files, and the installed version on your machine. 

You will want to run this with your own rfsrc object instead of the provided example objects.

**Comment by rshouv** [comment]
Thanks 
It worked!
