### ISSUE TITLE
plot.gg_survival has wrong legend

### ISSUE THREAD

**Issue by martin-weber** [ehrlinger/ggRandomForests#30]
When using gg_survival with the by= parameter and then plotting using plot.gg_survival the colors and the legends are not correct assigned to the groups.
To be precise, the error seams to be in kaplan.R, line 72ff.

**Comment by carlomengoli** [comment]
I also found this problem, running the code in "randomForestSRC-Survival.pdf"

**Comment by jequihua** [comment]
I too am facing this issue.

**Comment by ehrlinger** [comment]
Looking to correct this in the next version (2.1.1)

**Comment by ehrlinger** [comment]
Fixed in Version 2.2.1
