### ISSUE TITLE
Possible bug: plot.gg_interaction facet order

### ISSUE THREAD

**Issue by afb206** [ehrlinger/ggRandomForests#32]
Hi John,

When trying to produce variable interaction plots with plot.gg_interaction() I cannot get the order of the faceting to match the minimal depth rank order, with the set I am interested in being produced in alphabetical order instead.

I looked at several other plot methods for the package and found that 'variable' is often set to a factor after a gather step.  I tested if this could fix the issue by adding 
`gg_dta$variable <- factor(gg_dta$variable, levels=unique(gg_dta$variable))`
after line 143, which worked.

This doesn't exclude the (high) possibility that I am simply doing something wrong, but I thought I would send through the code. Thanks for the great package!

**Comment by ehrlinger** [comment]
I have apparently neglected to reply to this. I'm doing some updates now and will look at incorporating this into the code. Thanks for the suggestion.

**Comment by ehrlinger** [comment]
Release 2.2.0
